[general]
logging = 20
# setup = "setup211_simple_train_side_2"
db_host = "mongodb://linajeaAdmin:FeOOHnH2O@funke-mongodb4/admin"
db_name = "linajea_120828_setup211_simple_eval_side_1_400000"
sample = "120828"
setup_dir = "../unet_setups/setup211_simple_train_side_2"
seed = 42

[model]
net_name = "class_net"
network_type = 'vgg'
input_shape = [ 3, 8, 64, 64,]
pad_raw = [ 3, 30, 30, 30,]

num_fmaps = [8, 16, 32, 64]
fmap_inc_factors = [ 2, 2, 2, 1,]
downsample_factors = [ [ 2, 2, 2,], [ 2, 2, 2,], [ 2, 2, 2,], [ 1, 1, 1,],]
fc_size = 512
kernel_sizes = [ [ 3, 3,], [ 3, 3,], [ 3, 3, 3, 3,], [ 3, 3, 3, 3,],]

# efficientnet_size = "B10"

# resnet_size = '18'
# num_blocks = [3, 4, 4]
# use_bottleneck = true

activation = "relu"
padding = "SAME"
merge_time_voxel_size = 2

use_dropout = false
use_batchnorm = true
use_bias = true
use_global_pool = true

num_classes = 3
use_conv4d = true
make_isotropic = true

[train]
use_auto_mixed_precision = true
use_tf_data = false
val_log_step = 10
batch_size = 32
cache_size = 1024
max_iterations = 2000
checkpoint_stride = 1000
snapshot_stride = 250
profiling_stride = 500
# regularizer_weight = 0.00000001

[train.augment.elastic]
# control_point_spacing = [ 2, 10, 10,]
control_point_spacing = [ 5, 25, 25,]
jitter_sigma = [ 1, 1, 1,]
# jitter_sigma = [ 0.1, 0.1, 0.1,]
# jitter_sigma = [ 2, 2, 2,]
rotation_min = -10
rotation_max = 10
subsample = 4

[train.augment.intensity]
scale = [0.8, 1.2]
shift = [-0.005, 0.005]

[train.augment.simple]
mirror = [2, 3]
transpose = [2, 3]

[train.augment.noise_gaussian]
var = [0.2]

[train.augment.noise_saltpepper]
amount = [0.001]

[train.augment.jitter]
jitter = [ 0, 1, 5, 5,]

[train.job]
num_workers = 16
queue = 'gpu_rtx'


[optimizer]
# optimizer = "GradientDescentOptimizer"
# optimizer = "MomentumOptimizer"
optimizer = "AdamOptimizer"
[optimizer.args]
learning_rate = 0.0005
# momentum = 0.9
[optimizer.kwargs]
beta1 = 0.95
beta2 = 0.999
epsilon = 1e-8


[train_data]
use_database = false
[train_data.roi]
offset = [0, 0, 0, 0]
shape = [200, 385, 512, 712]
# if use_database = true:
[train_data.db_meta_info]
setup_dir = "some_setup_name"
checkpoint = 400000
cell_score_threshold = 0.3
# or data_source specific db_name
[[train_data.data_sources]]
# db_name = "db_name_str_A"
[train_data.data_sources.datafile]
filename = "/nrs/funke/malinmayorc/120828/120828_a.n5"
group='raw'
[[train_data.data_sources]]
# db_name = "db_name_str_B"
[train_data.data_sources.datafile]
filename = "/nrs/funke/malinmayorc/120828/120828_B.n5"
group='raw'


[test_data]
use_database = false
checkpoint = 10000
prob_threshold = 0.5
[test_data.roi]
offset = [0, 0, 0, 0]
shape = [200, 385, 512, 712]
# if use_database = true:
[test_data.db_meta_info]
checkpoint = 400000
cell_score_threshold = 0.3
setup_dir = "some_setup_name"
# or data_source specific db_name
[[test_data.data_sources]]
# db_name = "db_name_str"
[test_data.data_sources.datafile]
filename = "/nrs/funke/malinmayorc/120828/120828.n5"
group='raw'


[validate_data]
use_database = false
prob_thresholds = [ 0.1, 0.5, 0.75, 0.9, 0.99,]
checkpoints = [ 2000, 5000, 10000]
[validate_data.roi]
offset = [0, 0, 0, 0]
shape = [200, 385, 512, 712]
# if use_database = true:
# [validate_data.db_meta_info]
# checkpoint = 400000
# cell_score_threshold = 0.3
# setup = "some_setup_name"
# or data_source specific db_name
[[validate_data.data_sources]]
db_name = "db_name_strA"
[validate_data.data_sources.datafile]
filename = "/nrs/funke/malinmayorc/120828/120828_A.n5"
group='raw'
[[validate_data.data_sources]]
db_name = "db_name_strB"
[validate_data.data_sources.datafile]
filename = "/nrs/funke/malinmayorc/120828/120828_B.n5"
group='raw'


[predict]
batch_size = 64
[predict.job]
num_workers = 16
queue = 'gpu_rtx'

[evaluate]
max_samples = 200000
metric = "AP"
use_database = false
one_off = false
# distance_limit = 11
prob_threshold = 0.99
dry_run = true
find_fn = false
gt_db_name = 'linajea_120828_gt_side_1'
[evaluate.parameters]
matching_threshold = 15
# optional, can overwrite validate/test roi
frames = [0, 200]
# or
[evaluate.parameters.roi]
offset = [0, 0, 0, 0]
shape = [200, 385, 512, 712]
