model = "config_example_single_sample_model.toml"
predict = "config_example_single_sample_predict.toml"

[general]
logging = 20
db_host = "mongodb://linajeaAdmin:FeOOHnH2O@funke-mongodb4/admin?replicaSet=rsLinajea"
seed = 42
setup_dir = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/celegans_setups/experiments/mskc_test_1"
sparse = false



[extract]
block_size = [ 5, 512, 512, 512,]

[solve]
from_scratch = true
check_node_close_to_roi = false
parameters = "test.toml"


[evaluate]
from_scratch = false


[inference_data]
checkpoint = 10
cell_score_threshold = 0.2
[inference_data.data_source]
gt_db_name = "linajea_celegans_emb_fixed"
# voxel_size = [ 1, 5, 1, 1,]
db_name = "linajea_celegans_20220624_134111b"
[inference_data.data_source.datafile]
filename = "/nrs/funke/hirschp/mskcc_emb"
group = "volumes/raw_nested"
[inference_data.data_source.roi]
offset = [ 50, 0, 0, 0,]
shape = [ 10, 205, 512, 512,]

[extract.edge_move_threshold]
50 = 45
1000 = 35

[extract.job]
num_workers = 1
queue = "local"

[evaluate.parameters]
matching_threshold = 15

