[general]
logging = 20
db_host = "mongodb://linajeaAdmin:FeOOHnH2O@funke-mongodb4/admin?replicaSet=rsLinajea"
seed = 42
sparse = true
setup_dir = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/experiments/droso_test_1"

[model]
train_input_shape = [ 7, 60, 148, 148,]
predict_input_shape = [ 7, 80, 260, 260,]
unet_style = "split"
num_fmaps = [12, 12]
fmap_inc_factors = 3
downsample_factors = [[ 1, 2, 2,],
                      [ 2, 2, 2,],
                      [ 2, 2, 2,],]
kernel_size_down = [[ [3, 3, 3, 3], [3, 3, 3, 3],],
                    [ [3, 3, 3, 3], [3, 3, 3],],
                    [ [3, 3, 3], [3, 3, 3],],
                    [ [3, 3, 3], [3, 3, 3],],]
kernel_size_up = [[ [3, 3, 3], [3, 3, 3],],
                  [ [3, 3, 3], [3, 3, 3],],
                  [ [3, 3, 3], [3, 3, 3],],]
upsampling = "trilinear"
average_vectors = false
nms_window_shape = [ 3, 15, 15,]
path_to_script = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/mknet_drosophila.py"
latent_temp_conv = false
train_only_cell_indicator = false


[train]
# radius for binary map -> *2 (in world units)
# in which to draw parent vectors (not used if use_radius)
parent_radius = [ 0.1, 10.0, 10.0, 10.0,]
# sigma for Gauss -> ~*4 (5 in z -> in 3 slices) (not used if use_radius)
rasterize_radius = [ 0.1, 5.0, 5.0, 5.0,]
# upper bound for dist cell moved between two frames (needed for context)
move_radius = 10
cache_size = 1
use_radius = false
parent_vectors_loss_transition_offset = 20000
parent_vectors_loss_transition_factor = 0.01
path_to_script = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/train_drosophila.py"
max_iterations = 11
checkpoint_stride = 10
snapshot_stride = 5
profiling_stride = 10
use_auto_mixed_precision = false
use_swa = false
swa_every_it = false
swa_start_it = 49999
swa_freq_it = 1000
use_grad_norm = false
[train.job]
num_workers = 1
queue = "gpu_tesla"

[train.augment]
divisions = false
reject_empty_prob = 1.0
normalization = "default"
point_balance_radius = 1

[train.augment.elastic]
control_point_spacing = [ 5, 10, 10,]
jitter_sigma = [ 1, 1, 1,]
rotation_min = 0
rotation_max = 90
rotation_3d = false
subsample = 8
use_fast_points_transform = false

[train.augment.intensity]
scale = [ 0.9, 1.1,]
shift = [ -0.001, 0.001,]

[train.augment.simple]
mirror = [ 1, 2, 3,]
transpose = [ 2, 3,]


[optimizerTorch]
optimizer = "Adam"
[optimizerTorch.kwargs]
lr = 5e-4
betas = [0.95, 0.999]
eps = 1e-8


[predict]
path_to_script = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/predict.py"
path_to_script_db_from_zarr = "/groups/funke/home/hirschp/linajea_experiments/unet_setups/write_cells.py"
output_zarr_prefix = "/nrs/funke/hirschp/linajea_experiments"
write_to_zarr = false
write_to_db = true
write_db_from_zarr = false
processes_per_worker = 1
use_swa = false
[predict.job]
num_workers = 1
queue = "gpu_tesla"

[extract]
block_size = [ 7, 500, 500, 500,]
# edge_move_threshold = 40
use_mv_distance = true
[extract.edge_move_threshold]
-1 = 25


[extract.job]
num_workers = 1
queue = "local"

[solve]
from_scratch = true
non_minimal = false
greedy = false
write_struct_svm = false
check_node_close_to_roi = false
add_node_density_constraints = false
[solve.job]
num_workers = 1
queue = "local"
[[solve.parameters]]
weight_node_score =   -0.1      
selection_constant =  -0.425 
track_cost =          1.35
division_constant =   1
weight_edge_score =   0.0425
# weight_division =     
# weight_child =          
# weight_continuation = 

# cell_cycle_key = ''
block_size = [5, 500, 500, 500]
context = [2, 100, 100, 100]

# [solve.parameters_search_random]

# # weight_node_score =   []
# # selection_constant =  []
# # track_cost =          []
# # weight_division =     []
# # division_constant =   []
# # weight_child =        []
# # weight_continuation = []
# # weight_edge_score =   []

# # cell_cycle_key = []
# block_size = [[5, 500, 500, 500]]
# context = [[2, 100, 100, 100]]
# num_configs = 25
[solve.parameters_search_grid]
weight_node_score =   [-0.1, -0.05, -0.0, 0.05]
selection_constant =  [-0.35, -0.375, -0.4, -0.425]
track_cost =          [1.35, 1.375, 1.4, 1.425]
# weight_division =     []
division_constant =   [1.0]
# weight_child =        []
# weight_continuation = []
weight_edge_score =   [0.035, 0.0375, 0.04, 0.0425]

# cell_cycle_key = []
block_size = [[5, 500, 500, 500]]
context = [[2, 100, 100, 100]]
num_configs = 25

[evaluate]
from_scratch = false
[evaluate.parameters]
matching_threshold = 15
window_size = 200
validation_score = false
ignore_one_off_div_errors = false
fn_div_count_unconnected_parent = true
sparse = true
filter_polar_bodies = false
# [evaluate.parameters.roi]
# offset = [ 0, 0, 0, 0,]
# shape = [ 270, 512, 512, 512,]
# shape = [ 200, 512, 512, 512,]
[evaluate.job]
num_workers = 1
queue = "local"

[train_data]
voxel_size = [ 1, 5, 1, 1,]
[[train_data.data_sources]]
gt_db_name = "linajea_120828_gt_side_1"
exclude_times = [[200, 250]]
tracksfile = "/groups/funke/home/hirschp/linajea_experiments/data/120828/tracks/tracks_side_1_div_state.txt"
[train_data.data_sources.datafile]
filename = "/nrs/funke/malinmayorc/120828/120828.n5"
group = "raw"
[train_data.roi]
offset = [ 0, 0, 0, 0,]
shape = [ 450, 625, 603, 1272,]

[validate_data]
checkpoints = [ 400000,]
cell_score_threshold = 0.4
voxel_size = [ 1, 5, 1, 1,]
[[validate_data.data_sources]]
gt_db_name = "linajea_120828_gt_side_1"
db_name = "linajea_120828_setup211_simple_vald_side_1_400000_te"
tracksfile = "/groups/funke/home/hirschp/linajea_experiments/data/120828/tracks/tracks_side_1_div_state.txt"
[validate_data.data_sources.datafile]
filename = "/nrs/funke/malinmayorc/120828/120828.n5"
group = "raw"
[validate_data.roi]
offset = [ 200, 0, 0, 0,]
shape = [ 50, 625, 603, 1272,]

[test_data]
checkpoint = 10
cell_score_threshold = 0.4
voxel_size = [ 1, 5, 1, 1,]
[[test_data.data_sources]]
gt_db_name = "linajea_120828_gt_side_2"
db_name = "linajea_120828_setup211_simple_eval_side_2_400000_te"
tracksfile = "/groups/funke/home/hirschp/linajea_experiments/data/120828/tracks/tracks_side_2_div_state.txt"
[test_data.data_sources.datafile]
filename = "/nrs/funke/malinmayorc/120828/120828.n5"
group = "raw"
[test_data.roi]
offset = [ 50, 0, 0, 0,]
shape = [ 5, 625, 603, 1272,]
