model = "config_example_model_minimal.toml"

[general]
logging = 20
db_host = "mongodb://linajeaAdmin:FeOOHnH2O@funke-mongodb4/admin?replicaSet=rsLinajea"
setup_dir = "example_simple_2"
sparse = true

[train_data]
voxel_size = [ 1, 5, 1, 1,]
[[train_data.data_sources]]
gt_db_name = "linajea_120828_gt_side_1"
exclude_times = [[200, 250]]
tracksfile = "/groups/funke/home/hirschp/linajea_experiments/data/120828/tracks/tracks_side_1_div_state.txt"
divisionsfile = "/groups/funke/home/hirschp/linajea_experiments/data/120828/tracks/tracks_side_1_div_state.txt"
daughtersfile = "/groups/funke/home/hirschp/linajea_experiments/data/120828/tracks/daughter_cells_side_1.txt"
[train_data.data_sources.datafile]
filename = "/nrs/funke/malinmayorc/120828/120828.n5"
group = "raw"
[train_data.roi]
offset = [ 0, 0, 0, 0,]
shape = [ 450, 625, 603, 1272,]

[train]
# radius for binary map -> *2 (in world units)
# in which to draw movement vectors (not used if use_radius)
object_radius = [ 0.1, 10.0, 10.0, 10.0,]
# upper bound for dist cell moved between two frames (needed for context)
move_radius = 10
# size of cell indicator blobs
# sigma for Gauss -> ~*4 (5 in z -> in 3 slices) (not used if use_radius)
rasterize_radius = [ 0.1, 5.0, 5.0, 5.0,]
max_iterations = 21
checkpoint_stride = 10
use_auto_mixed_precision = true