weight_node_score =   [-13, -17, -21]
selection_constant =  [6, 9, 12]
track_cost =          [7,]
weight_division =     [-8, -11]
division_constant =   [6.0, 2.5]
weight_child =        [1.0, 2.0]
weight_continuation = [-1.0]
weight_edge_score =   [0.35]
val = [true]
block_size = [[15, 512, 512, 712]]
context = [[2, 100, 100, 100]]